### PR TITLE
Added a C++ Code to Reverse a path in a Binary Search Tree

### PR DESCRIPTION
**Pull request by shubhamayush12**

### CODE REVIEW

**Comment by manisha069** [comment]
Hello and congratulations on joining in on HacktoberFest!

**Comment by shubhamayush12** [comment]
ma am it is still showing in hacktoberfest page as pull request not accepted. will you please tell me ma am what is the issue?

**Comment by manisha069** [comment]
Have your issues been resolved?

**Comment by shubhamayush12** [comment]
yes ma am

**Comment by manisha069** [comment]
Great! (No need to use Ma'am)

**Comment by shubhamayush12** [comment]
Ok

**Pull request merged**
