### PR TITLE
Create Standardcalculator.py

### PR DESCRIPTION
**Pull request by abhishek213-alb**

### CODE REVIEW

**Comment by manisha069** [comment]
Hello and congratulations on joining in on HacktoberFest!

**Comment by abhishek213-alb** [comment]
@manisha069 Thanks can I contribute more to this repo

**Comment by manisha069** [comment]
Srely! But do make sure you bring something new to the repo and not code that has already been submitted!

**Comment by abhishek213-alb** [comment]
@manisha069 sure

**Pull request merged**
