### PR TITLE
created insertion

### PR DESCRIPTION
**Pull request by Amanuttam1192**
A basic insertion sort program,which is simple yet  confusing

### CODE REVIEW

**Comment by manisha069** [comment]
Hello and congratulations on joining in on HacktoberFest! Do ⭐ the repo and share with your friends.

Simple yet confusing lol

**Comment by Amanuttam1192** [comment]
Mam can you please tell what is the review period in hacktober fest,like
its showing that pr matures in 14 days🤔🤔

**Comment by manisha069** [comment]
1. No need to use ma'am
2. yes the mature period or review period is for 14 days after which it should start counting towards your submission. 
If you have made good and proper PRs and they have been accepted into repos with 'hacktoberfest-accepted' label then you do not have to worry about anything.

**Comment by Amanuttam1192** [comment]
Thank you for the clarification.

**Pull request merged**
