### PR TITLE
Added counting substrings in strings

### PR DESCRIPTION
**Pull request by Mudit88**

### CODE REVIEW

**Comment by manisha069** [comment]
You are using python...doesn't this work?
image

**Comment by Mudit88** [comment]
Yes ma'am instead of writing a builtin function I tried to explain the
working behind this builtin function (according to my knowledge), by the
way ma'am you will get the same answer by my code also

**Comment by Mudit88** [comment]
see this contradiction with count maam

**Comment by manisha069** [comment]
Oh great Mudit!

PS. dont call me ma'am😅😅

**Pull request merged**
