### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by SPal-14**
If you like it, please accept my pull request...

### CODE REVIEW

**Comment by manisha069** [comment]
Hello and congratulations on joining in on HacktoberFest!
Due to some issues, your code has not been uploaded properly.

image

**Comment by SPal-14** [comment]
Yes, I have noticed it....So, I request you to follow these steps:
Step 1: Click those three dotted line at the extreme right..( beside
verified)
Step 2: Click 'view file'
Step 3: Click 'download'
It will get downloaded ...
Please don't forget to reply whether it worked or not....🙏🙏🙏

**Comment by manisha069** [comment]
I see thanks...

however, the code that you have submitted i.e. Binary Search has already been submitted and unfortunately I cannot merge your PR.

I would be happy to merge a PR if you submit a code that has not been submitted yet and please make it a proper file and not .docx

**Comment by manisha069** [comment]
If you have any issues let me know

**Comment by SPal-14** [comment]
Thanks for replying....
Okay, I will try to upload something new...but I think, there are many
other programs other than binary search...i.e....stack, queue, etc. I may
upload Saddle Point program....Yes, if you don't need that saddle point
one...feel free to tell me..I will try another one...

**Pull request closed without merging**
