### PR TITLE
Added Algorithms and updated readme

### PR DESCRIPTION
**Pull request by soham117**
I am not very much familiar with markdown so pls guide me if any change required

### CODE REVIEW

**Comment by manisha069** [comment]
Soham It's all great but...why did you make a PR today itself?
PRs made before 1st Oct would not be counted🤐🤐

**Comment by soham117** [comment]
It will be madam

**Comment by manisha069** [comment]
Okay but I'll merge and Label tomorrow..is that fine?

**Comment by soham117** [comment]
PR is reflecting on HacktoberFest21 website

**Comment by soham117** [comment]
No issues if u want to merge tomorrow

**Comment by manisha069** [comment]
Also I used this article to help me with Markdown you can refer to it too...
https://guides.github.com/features/mastering-markdown/

**Comment by soham117** [comment]
Thank you very much for accepting my PR and also for providing the article 😀

**Comment by manisha069** [comment]
My PLeasure!

**Pull request merged**
