### PR TITLE
Dijkstra

### PR DESCRIPTION
**Pull request by Kaustuv942**

### CODE REVIEW

**Comment by Kaustuv942** [comment]
Please accept my PR

**Comment by manisha069** [comment]
Hello and congratulations on joining in on HacktoberFest!

Lovely to see you making PRs and actively participating in HacktoberFest, Please make the following changes and submit a new PR:
1. It is noticed you have submitted Dijksta's Algorithm under "Code" sub directory, kindly make a fresh PR with the cod eunder "Algorithm" directory!

**Comment by manisha069** [comment]
For any doubts let me know in the comments.

**Comment by Kaustuv942** [comment]
sure thank you

**Pull request closed without merging**
