### PR TITLE
Binary Exponentiation

### PR DESCRIPTION
**Pull request by Sun-0321**
Hey there! 
This is Sundar. I have added BINARY EXPONENTIATION.

Hope you would like it and merge it with you repository and consider this as my contribution for HACKTOBERFEST - 2021.

### CODE REVIEW

**Comment by manisha069** [comment]
Hello and congratulations on joining in on HacktoberFest!

**Comment by Sun-0321** [comment]
Why is your project excluded?

**Comment by manisha069** [comment]
Yeah unfortunately Team Hacktoberfest is going around blocking certain kinds of Repos that are DSA Oriented.

**Comment by manisha069** [comment]
image

**Pull request merged**
